### ISSUE TITLE
More general approach

### ISSUE THREAD

**Issue by SlimeDog** [TeamVK/JSEngine#1]
I asked this in the BigDoorsOpener discussion forum
```
... will BDO work with other Nashorn providers, say JSEngine?
```
The [response](https://www.spigotmc.org/threads/big-doors-opener.448183/page-4#post-4172741) (with a few formatting and spelling corrections) was
```
No, it won't work with JSEngine sadly. That because it uses an individual way, which is not independent to its implementor.
I am already using the most independent way with the ServiceManager. The JSEngine Plugin requires that I know that the plugin exists.

My NashornJs engine does not requires to know its name or if it exists. It registers a service which everyone can use at runtime without calling the plugin or anything.

BDO will work with every Nashorn engine provider which registers a ScriptEngineManager as a bukkit service. At least as long as the plugin implements it properly and registers it as early as possible.

The JSEngine even requires that I add it as a compileOnly dependency. Which is not required when using NashornJS by me. It's doing exactly what I am trying to avoid at all costs.
```

Perhaps JSEngine should address these issues, so that it can be used in a more general way.

**Comment by vk2gpz** [comment]
well, javax.script is independent from Minecraft's service.  It is not necessary to use minecraft's service provider to use any script engine.

However, I could also add the use of bukkit service in JSEngine.

**Comment by vk2gpz** [comment]
JSEngine now provides three different ways to access JS one as a generic Java library and two for Minecraft plugin specific.

**Comment by SlimeDog** [comment]
Thanks. So will BigDoorsOpener -- or any other consumer of ScriptEngineManager -- now work without change on Java 16, with JSEngine, in place of NashornJs?

**Comment by vk2gpz** [comment]
if BDO is using Bukkit's ServicesManager, then it should.

**Comment by SlimeDog** [comment]
Great to hear. I'll test when I'm back at the computer.

**Comment by SlimeDog** [comment]
Confirmed that BigDoorsOpener 2.4.1b works with JSEngine 3.0.1 (no doubt using ServicesManager mode) on Paper 1.16.5-735. Thanks.

**Comment by vk2gpz** [comment]
Thanks for checking.
